# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10cd0cc645f7247fe0482bef87fb938dc1ef5580ffbc6a58f1e9a932b52e7d392b275ab7776942241fd95949f6ca1eab431e495994a743682edd7ee4db3bacd4

test:
  secret_key_base: 5ac3b22b7610b2701453ff5f6c25b9132d5794b8f7b7ae079faebbd186ed8bc7b4c894e5ff1600bc3c3f049695562de4ac8e1f6170bef347ec15cee79c8d2cdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
